### PR TITLE
Add OpenBMC FRU VPD example

### PR DESCRIPTION
**Pull request by youhour**
Adding OpenBMC FRU VPD example.
Also removing UD keyword from OSYS record in system VPD template.

bug:  NA
branch:  master

Signed-off-by: Michael Y. Lim <youhour@us.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/vpdtools/12)

### CODE REVIEW

**Comment by youhour** [comment]
Adding a generic OpenBMC FRU VPD template.

**Comment by youhour** [comment]
Accidetally closed it earlier.

**Comment by thejta** [comment]
Can you split this into two commits?  One to undo the UD keyword and then one to add the new template.  They seem unrelated to go into the same commit.

The new template dir also needs to fix capitalization to be consistent.  I would prefer all lower case "openbmc", but the properly capitalized "OpenBMC" works too.

**Comment by youhour** [comment]
OK.  I can do that.  What do I need to do to update the change with your suggestion?  Do you need to reject this change first?

**Comment by thejta** [comment]
Closing pull request, new one will come with suggested changes.

**Pull request closed without merging**
